language: python
python:
- '3.4'
env:
  matrix:
    - FORMAT=hst
    - FORMAT=fxt
addons:
  apt:
    packages:
    - realpath
    - pv
notifications:
  email: false
before_install:
- set -e
install: 
before_script:
- curl -o Makefile https://raw.githubusercontent.com/FX31337/FX-BT-Data-Test/master/Makefile
script:
- make $FORMAT
after_success: 
after_failure:
- sudo apt-get -qy install tree && - tree -d -L 6
- env
after_script:
- pwd
deploy:
  provider: releases
  api_key:
    secure: wZfruJ+KVDfyOGnJbhE2PiYmcHoSY470hQEumXeQ+pFnv+803xXmKBJ/VmCZtbbbVR0hxuucsgpM7srCn5Emz2PkpiCUKwaXTKZqnk+L3BVHdlP2gY0wZoHKRh5znNeYB24XyANlE5IEUAot7B5vmBj6Yo/F0zirIm8hltjFryqQhSNWyGyzhoE4Mkpp2Xwlqr4SqHhkgHSN/WphLsbmZGWHVSYpJAot4nGHlxwZF0Xw0RIRSmO3wCWCHVQIYI5AOOjZJre9t+WaKHfOqlmvrqgw1y6PzLSAtcApUFJoy7DGNTkpQTTuXpU+MuDoacUyaelMbXxGQm68fxtZx4gtEv3iCWjlRQFkYMqjYpaf5FkgW/a9L2Y+DiW/f1QeJzstyZn3Im6MrL9wPat7V+VhhRTv1+Fnpj1+hqTuKydtOtBVvCAPwDZO0jjXINjkhzEMwLP1toHSkGP6G10G4ZP2CMTtxcCXSvoZpeGroZm6dgNKA/yeLwYzg/TrQBM5152EcKtyOH5Tv5Vs7MHEUKT+cZ249cpLmWH0DSg2Hws9gQk129QAKBzG/36ENLalhrC8uCl5agxFOyfd79SvI8aevrMZgPIYJ2UZELVGD7wplIiMHMhbqXlThRt7gfrnzCBGhP4foCaHG9DtKlqJEDumZNpfCtI/YHYyx6chEtTpgpk=
  file:
    - "*.hst.gz"
    - "*.fxt.gz"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: FX31337/FX-BT-Data-EURUSD-DS
    tags: true
after_deploy:
- make clean
